os: linux
language: java
jdk: oraclejd11

git:
  quiet: true

before_install:
  - "chmod +x gradlew"

script:
  - "./gradlew clean"
  - "./gradlew assemble"
  - "./gradlew release"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: "release/*.jar"
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
